### PR TITLE
Fixed compilation

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
```
In file included from /mnt//cpp/src/lora_cpp.hpp:35,
                 from /mnt//cpp/src/stable_diffusion.hpp:30,
                 from /mnt//cpp/src/main.cpp:5:
/mnt//_deps/safetensors-src/safetensors.h: In function ‘int eat_string(char**, char*, safetensors_Str*)’:
/mnt//_deps/safetensors-src/safetensors.h:313:48: error: designator order for field ‘safetensors_Str::len’ does not match declaration order in ‘safetensors_Str’
  313 |  *out = (safetensors_Str) {.ptr=start, .len=len};
      |                                                ^
/mnt//_deps/safetensors-src/safetensors.h: In function ‘char* more_memory(safetensors_File*)’:
/mnt//_deps/safetensors-src/safetensors.h:373:19: error: invalid conversion from ‘void*’ to ‘safetensors_TensorDescriptor*’ [-fpermissive]
  373 |   out->tensors  = new_tensors;
      |                   ^~~~~~~~~~~
      |                   |
      |                   void*
/mnt//_deps/safetensors-src/safetensors.h:377:19: error: invalid conversion from ‘void*’ to ‘safetensors_MetadataEntry*’ [-fpermissive]
  377 |   out->metadata = new_metadata;
      |                   ^~~~~~~~~~~~
      |                   |
      |                   void*
/mnt//_deps/safetensors-src/safetensors.h: In function ‘char* safetensors_file_init(void*, int64_t, safetensors_File*)’:
/mnt//_deps/safetensors-src/safetensors.h:458:63: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
  458 |  #define ST_ERR(message) return out->error_context=t, (message);
      |                                                               ^
      |                                                               |
      |                                                               const char*
/mnt//_deps/safetensors-src/safetensors.h:461:22: note: in expansion of macro ‘ST_ERR’
  461 |  if (!eat(&t,e,'{')) ST_ERR("Expected '{'");
      |                      ^~~~~~
/mnt//_deps/safetensors-src/safetensors.h:458:63: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
  458 |  #define ST_ERR(message) return out->error_context=t, (message);
      |                                                               ^
      |                                                               |
      |                                                               const char*
/mnt//_deps/safetensors-src/safetensors.h:473:4: note: in expansion of macro ‘ST_ERR’
  473 |    ST_ERR("Expected tensor name");
      |    ^~~~~~
/mnt//_deps/safetensors-src/safetensors.h:458:63: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
  458 |  #define ST_ERR(message) return out->error_context=t, (message);
      |                                                               ^
      |                                                               |
      |                                                               const char*
/mnt//_deps/safetensors-src/safetensors.h:475:4: note: in expansion of macro ‘ST_ERR’
  475 |    ST_ERR("Expected colon after tensor name");
      |    ^~~~~~
/mnt//_deps/safetensors-src/safetensors.h:458:63: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
  458 |  #define ST_ERR(message) return out->error_context=t, (message);
      |                                                               ^
      |                                                               |
      |                                                               const char*
/mnt//_deps/safetensors-src/safetensors.h:500:6: note: in expansion of macro ‘ST_ERR’
  500 |      ST_ERR("Expected a key-value pair");
      |      ^~~~~~
/mnt//_deps/safetensors-src/safetensors.h:506:14: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
  506 |              "Expected a string value for a metadata entry";
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              |
      |              const char*
/mnt//_deps/safetensors-src/safetensors.h:458:63: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
  458 |  #define ST_ERR(message) return out->error_context=t, (message);
      |                                                               ^
      |                                                               |
      |                                                               const char*
/mnt//_deps/safetensors-src/safetensors.h:519:7: note: in expansion of macro ‘ST_ERR’
  519 |       ST_ERR("Expected comma");
      |       ^~~~~~
/mnt//_deps/safetensors-src/safetensors.h:458:63: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
  458 |  #define ST_ERR(message) return out->error_context=t, (message);
      |                                                               ^
      |                                                               |
      |                                                               const char*
/mnt//_deps/safetensors-src/safetensors.h:527:5: note: in expansion of macro ‘ST_ERR’
  527 |     ST_ERR("Expected comma");
      |     ^~~~~~
/mnt//_deps/safetensors-src/safetensors.h:458:63: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
  458 |  #define ST_ERR(message) return out->error_context=t, (message);
      |                                                               ^
      |                                                               |
      |                                                               const char*
/mnt//_deps/safetensors-src/safetensors.h:531:2: note: in expansion of macro ‘ST_ERR’
  531 |  ST_ERR("Unterminated header");
      |  ^~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-permissive’
```

### CODE REVIEW

**Comment by hsnyder** [comment]
Hi @ilya-lavrenov, thanks for the pull request. Your changes, though, will make this file C++ only (because of the `const_cast<char*>`) whereas originally it was designed for C. I would like to support both languages, though. if you have time to replace the const_cast with something C compatible that would be great. If not, I can do so sometime next week.

**Comment by ilya-lavrenov** [comment]
Hi @hsnyder 
Thank you for the review. I've applied your suggestion, please, have a look once again

**Comment by ilya-lavrenov** [comment]
Hi @hsnyder 
Could you please check once again?

**Comment by hsnyder** [comment]
Hi @ilya-lavrenov sorry for the delay. I've merged your PR. Thanks a lot for contributing!

**Pull request merged**
